quiz/urls.py
from django.urls import path

from . import views

app_name = 'quiz'

urlpatterns = [
# ex: /polls/
   path('', views.index, name='index'),
# ex: /polls/5/
   path('<int:question_id>/', views.detail, name='detail'),
# ex: /polls/5/results/
   path('<int:question_id>/results/', views.results, name='results'),
# ex: /polls/5/vote/
   path('<int:question_id>/vote/', views.vote, name='vote'),

   path('add_question', views.add_question, name='add_question'), 

   path('delete_question', views.delete_question, name='delete_question'), 
]

test29/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView


urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('quiz/', include('quiz.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

quiz/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    
    question_text = models.CharField(max_length=200)
    create_question_by_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    ans = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    point = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class User(models.Model):
   
    username = models.CharField(max_length=200)
    user_point = models.IntegerField(default=0)
    
    def __str__(self):
        return self.username

quiz/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


from .models import Question, Choice, User
from django.utils import timezone

def index(request):
    """ show question sort by id """
    
    latest_question_list = Question.objects.order_by('id')[:10]    
    return render(request, 'quiz/index.html', {'latest_question_list': latest_question_list})

  
def detail(request, question_id):
    """ show choice of question """
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'quiz/detail.html', {'question': question})


def results(request, question_id):
    """ show number people ans question and point user """
    question = get_object_or_404(Question, pk=question_id)
    
    user_from_db = User.objects.values('username', 'user_point')
    #user_from_db = User.objects.get(name='Silver')
    #print(user_from_db.username)
    return render(request, 'quiz/results.html', {'question': question, 'username_show_html' : user_from_db})


def add_question(request):
    """ add question and choice to database """
    new_text_question = "No Question add to database"
    new_text_choice1 = "No Choice add to database"
    new_text_choice2 = "No choice add to database"
    choice1_true_false = ""
    choice2_true_false = ""
    create_question_by = ""
    
    #pass value from html to control (python)
    if request.method == 'POST':
       new_text_question = request.POST['new_text_question']
       new_text_choice1 = request.POST['new_text_choice1']
       new_text_choice2 = request.POST['new_text_choice2']
       choice1_true_false = request.POST['choice1']
       choice2_true_false = request.POST['choice2']
       create_question_by = request.POST['create_question_by']
       
       #add question
       q = Question(question_text= new_text_question, create_question_by_text= create_question_by, pub_date=timezone.now())
       q.save()
       q.choice_set.create(choice_text=new_text_choice1, ans=choice1_true_false, votes=0)
       q.choice_set.create(choice_text=new_text_choice2, ans=choice2_true_false, votes=0)
   
    # pass value form control (python) to html
    show_question = { 
                   'quest_text'   : new_text_question,
                   'choice1_text' : new_text_choice1,
                   'choice2_text' : new_text_choice2,
                   'choice1_true_false' : choice1_true_false,
                   'choice2_true_false' : choice2_true_false,
                   'create_question' : create_question_by
    }
    return render(request,'quiz/add_question.html',show_question )


def delete_question(request):
    latest_question_list = Question.objects.order_by('id')[:10]    
    delete_quest_text = ""
    create_question_by = ""
    check_create_question = "admin"
    

    
    #pass value from html to control (python)
    if request.method == 'POST':
       delete_quest_text = request.POST['delete_quest_text']
       create_question_by = request.POST['create_question_by']
       
       #delete question
       
       if(create_question_by == check_create_question): 
          d = Question.objects.get(question_text=delete_quest_text)
          #print(d.choice_set.all())
          d.choice_set.all().delete()
          #print(d.choice_set.all())
          d.delete()
       else:
           return render(request, 'quiz/no_delete_quiz .html', {
                 
                 'error_message': "You can't delete that Question.", 
           })
    # pass value form control (python) to html
    show_delete_question = { 
                   'delete_quest_text'   : delete_quest_text,
                   'latest_question_list': latest_question_list,
                   'create_question' : create_question_by
    }


    return render(request, 'quiz/delete_question.html',show_delete_question )


def vote(request, question_id):
    """ count number of ans, add user ans question, count point """
    username_now = 'Unknow'
    point_now = 0
    question = get_object_or_404(Question, pk=question_id)
    try:


        if request.method == 'POST':
           username_now = request.POST['username']

           if(username_now == ''):
              return render(request, 'quiz/no_ans_quiz.html', {
                 'question': question,
                 'error_message': "You didn't put your name.", 
              })

           elif (User.objects.filter(username = username_now)):
              user = User.objects.get(username = username_now)
              user.username = username_now 
              user.save()
           else:
              user = User(username=username_now, user_point=0)
              user.save()

        

        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        check_ans = question.choice_set.get(choice_text = selected_choice)
        check_true_false = question.choice_set.get(ans ='True')
        user = User.objects.get(username = username_now)
        

        if(check_ans == check_true_false):
           user.user_point += 1
           user.save() 
        else:
           user.user_point += 0
           user.save()

    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'quiz/no_ans_quiz.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        
        
        
        return HttpResponseRedirect(reverse('quiz:results', args=(question.id,)))

quiz/templates/home.html
<html>
   <head> 
      <title>Home quiz test29</title>
   </head>
   
   <body>
     <h1>Welcome to HomePage Quiz Test29</h1><br>
     <a href="/quiz/" id="to_page_quiz" >Go To Quiz</a>

   </body>

</html>

quiz/templates/quiz/add_question.html
<html>
    <head>
        <title>Add question</title>
    </head>
    <body>
        
       
        <h1>Add question</h1>

            <form action="add_question" method = "POST">
               Create question by:<br>
                <input type="text" name="create_question_by" id="create_question_by" placeholder="Your name"><br><br>
               {% csrf_token %}
               
               Question:<br>
              
                <input type="text" name="new_text_question" id="new_text_question" placeholder="Your Question"><br><br>
               
                <input type="text" name="new_text_choice1" id="new_text_choice1" placeholder="Your choice 1">
                <input type="radio" name="choice1" value="True" id="choice1_true" > True
                <input type="radio" name="choice1" value="False" id="choice1_false"> False<br>

                <input type="text" name="new_text_choice2" id="new_text_choice2" placeholder="Your choice 2">
                <input type="radio" name="choice2" value="True" id="choice2_true" > True
                <input type="radio" name="choice2" value="False" id="choice2_false"> False<br><br>
                
                <input type="submit" value="Submit" id="submit"><br>
  
            </form> 
            
        <h2> New Question </h2>
       <p> {{ quest_text }} Create by {{ create_question }}
          <ul>
             <li> {{ choice1_text }} ( {{ choice1_true_false }} )</li>
             <li> {{ choice2_text }} ( {{ choice2_true_false }} )</li> </p>
          </ul>     
       <li><a href="/quiz/" id="back_home_page" >Home page?</a></li>
           

    </body>
</html>

quiz/templates/quiz/delete_question.html
<html>
    <head>
        <title>Delete Question</title>
    </head>
    <body>
        
       
        <h1>Delete Question</h1>
        <h2>Question in webapp</h2>
           {% if latest_question_list %}
               <ul>
               {% for question in latest_question_list %}
                   {{forloop.counter}}. {{ question.question_text }}<br>
               {% endfor %}
               </ul>
            {% else %}
                <p1>No quiz are available.</p1><br><br>
            {% endif %}

         <h3>Delete Form</h3>
             <form action="delete_question" method = "POST">
               Create question by:<br>
                <input type="text" name="create_question_by" id="create_question_by" placeholder="Your name"><br><br>
               {% csrf_token %}
               
               Question:<br>
              
                <input type="text" name="delete_quest_text" id="delete_quest_text" placeholder="Your Question"><br><br>
               
                
                <input type="submit" value="Submit" id="submit"><br>
  
            </form> 

             
             <h4> Delete Question </h4>
       <p> Delete by: {{ create_question }}<br> 
           Question delete: {{ delete_quest_text }} </p>
     
             <a href="/quiz/" id= "back_home">   Back to homePage ? </a><br>
              
             
      

    </body>
</html>

quiz/templates/quiz/detail.html
<html>
   <head>
     <title>Choice question</title>
   </head>
   
   <body>
     <h1>{{ question.question_text }}</h1>

     {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

     <form action="{% url 'quiz:vote' question.id %}" method="post">
        Your name: <input type="text" name="username" id="username" placeholder="Your name"><br>
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
           <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
           <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        
        <input type="submit" id="vote" value="Vote" />
     </form>

   </body>
</html>

quiz/templates/quiz/index.html
<html>
    <head>
        <title>quiz test29</title>
    </head>
    <body>
        
       
        <h1>Quiz</h1>
 
           {% if latest_question_list %}
               <ul>
               {% for question in latest_question_list %}
                   {{forloop.counter}}. <a href="{% url 'quiz:detail' question.id %}" id="quiz_select1">{{ question.question_text }}</a><br>
               {% endfor %}
               </ul>
            {% else %}
                <p1>No quiz are available.</p1><br><br>
            {% endif %}

         
             <a href="add_question" id= "add_question">   You can add Question </a><br>
              <a href="delete_question" id= "delete_question">   Only admin can delete Question </a>
             
      

    </body>
</html>

quiz/templates/quiz/no_ans_quiz.html
<html>
    <head>
        <title>No Ans question</title>
    </head>
    <body>
        
       
        <h1>{{ error_message }} </h1>
        <h2>{{question}} </h2>
        
           
                      
        <li> <a href="{% url 'quiz:detail' question.id %}" id="vote_again" >Please Ans again?</a></li> </br> 
        <li><a href="/quiz/">Home page?</a></li>
           

    </body>
</html>

quiz/templates/quiz/no_delete_quiz .html
<html>
    <head>
        <title>You can't delete question</title>
    </head>
    <body>
        
       
        <h1>{{ error_message }} </h1>
        
        
           
                      
        
        <li><a href="/quiz/">Home page?</a></li>
           

    </body>
</html>

quiz/templates/quiz/results.html
<html>
   <head>
      <title>results question</title>
   </head>

   <body>
      
      
         <h1>results {{ question.question_text }} Create by {{ question.create_question_by_text }}</h1>
      
      <ul>
         {% for choice in question.choice_set.all %}
         <li> Choice: <b>{{ choice.choice_text }}</b> is <b>{{ choice.ans }}</b> <br> Number of people select choice {{ choice.votes }}   </li><br>
         {% endfor %}
      </ul>

      {% if username_show_html %}
               <ul>
               {% for user in username_show_html %}
                   {{forloop.counter}}. {{ user.username }} you have point {{ user.user_point }}</a><br>
               {% endfor %}
               </ul>
            {% else %}
                <p>No quiz are available.</p> 
            {% endif %}
     

      <li><a href="{% url 'quiz:detail' question.id %}" id="vote_again" >Ans again?</a></li>

      <li><a href="/quiz/">Home page?</a></li>

   </body>

</html>